include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - pre
  - download
  - build
  - slim
  - full
  - scan
  - notify

download:pgp:
  stage: pre
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  before_script:
    - apk add --no-cache gnupg linux-headers
  script:
    - |
      if [ -f keys.out ]; then
        gpg --import keys.out
      fi
    - |
      for key in `cat gpgkeys.txt`; do
        gpg --list-keys ${key} || (gpg --keyserver pgp.mit.edu --recv-keys "$key" || gpg --keyserver keyserver.pgp.com --recv-keys "$key" || gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key")
      done
    - gpg --export > keys.out
  tags:
    - jitesoft
  cache:
    key: nodejs.gpg.keyring
    paths:
      - keys.out
  artifacts:
    paths:
      - keys.out
    expire_in: 1 day

download:versions:
  stage: pre
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
    NODE_VERSIONS: "10 12"
  before_script:
    - apk add --no-cache grep
  script:
    - mkdir versions
    - |
      for version in $NODE_VERSIONS; do
        wget -qO- https://nodejs.org/dist/latest-v${version}.x/ | grep -oP "(?<=>node-v)(([0-9]{0,3}(\.?)){3})" | awk 'NR==1{print $1}' > versions/${version}.txt
      done;
  only:
    refs:
      - master
  tags:
    - jitesoft
  artifacts:
    paths:
      - versions/*.txt
    expire_in: 1 day

download:tars:
  stage: download
  dependencies:
    - download:versions
    - download:pgp
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  before_script:
    - apk add --no-cache curl grep gnupg
    - gpg --import keys.out
  script:
    - |
      for VERSION_FILE in versions/*.txt; do
        VERSION=$(cat ${VERSION_FILE})
        curl -OsS https://nodejs.org/dist/v${VERSION}/node-v${VERSION}.tar.xz
        curl -OsS https://nodejs.org/dist/v${VERSION}/SHASUMS256.txt
        curl -OsS https://nodejs.org/dist/v${VERSION}/SHASUMS256.txt.sig
        gpg --verify SHASUMS256.txt.sig SHASUMS256.txt
        grep " node-v${VERSION}.tar.xz\$" SHASUMS256.txt | sha256sum -c -
        mv node-v${VERSION}.tar.xz versions/node-v${VERSION}.tar.xz
      done;
  tags:
    - jitesoft
  only:
    refs:
      - master
  artifacts:
    paths:
      - versions/*.tar.xz
      - versions/*.txt
    expire_in: 1 day

.build:binary: &node_binary
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  dependencies:
    - download:tars
  before_script:
    - apk add --no-cache build-base binutils-gold git python linux-headers ccache libstdc++ xz gnupg curl
    - if [ ! -d "result" ]; then mkdir result; fi
    - if [ ! -d "ccache" ]; then mkdir ccache; fi
    - mkdir -p node-src
  script:
    - PATH="/usr/lib/ccache/bin:$PATH"
    - CCACHE_RECACHE="yes"
    - CCACHE_DIR="$(pwd)/ccache"
    - NODE=$(cat versions/${NODE_VERSION}.txt)
    - ccache -s
    - tar -Jxf versions/node-v${NODE}.tar.xz -C node-src --strip-components=1
    - cd node-src
    # Only print every 100th line, build.log is added to out directory, err is piped to stdout.
    - make -j4 binary V= DESTCPU="${ARCHITECTURE}"${EXTRA_FLAGS} ARCH="${ARCHITECTURE}" VARIATION="musl" RELEASE_URLBASE="https://gitlab.com/jitesoft/dockerfiles/node-base" 2>&1 | tee ../result/build.log | awk 'NR%100==0 {print NR,$0}'
    - cd ..
    - ccache -s
    - ccache -s > result/ccache.log
    - mv node-src/node-*.tar.?z result/
  cache:
    paths:
      - ccache/
    key: node.build.ccache-${BUILD_TYPE}
  artifacts:
    paths:
      - result/*.log
      - result/*.tar.*
    expire_in: 10 days
  tags:
    - jitesoft
    - ">4x64"
    - ">8gb"

.build:slim: &slim_build
  stage: slim
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - NODE=$(cat versions/${NODE_VERSION}.txt)
    - NODE_SHORT=$(echo ${NODE} | cut -d'.' -f1)
    - echo "Building slim image for node v ${NODE} - short name ${NODE_SHORT}"
    - TAGS=$(helper taglist "${CI_REGISTRY_IMAGE},jitesoft/node-base" "${NODE}-slim,${NODE_SHORT}-slim,${EXTRA_TAGS}${BUILD_TYPE}-slim")
    - docker buildx build --platform linux/amd64 --push ${TAGS} --build-arg NODE_VERSION=${NODE} --progress plain -f slim/Dockerfile .
  only:
    refs:
      - master
  tags:
    - jitesoft
    - buildx
    - amd64

.build:full: &full_build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  stage: full
  script:
    - NODE=$(cat versions/${NODE_VERSION}.txt)
    - NODE_SHORT=$(echo ${NODE} | cut -d'.' -f1)
    - TAGS=$(helper taglist "${CI_REGISTRY_IMAGE},jitesoft/node,jitesoft/node-base" "${NODE},${NODE_SHORT},${EXTRA_TAGS}${BUILD_TYPE}")
    - docker buildx build --platform linux/amd64 --push ${TAGS} --build-arg NODE_VERSION=${NODE} -f full/Dockerfile .
  only:
    refs:
      - master
  tags:
    - jitesoft

trigger_build:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: notify
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${NOTIFY_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4048627/trigger/pipeline"
  only:
    refs:
      - master

build:src:latest:
  variables:
    CCACHE_DIR: "/root/.ccache"
    BUILD_TYPE: "latest"
    NODE_VERSION: "12"
    GIT_STRATEGY: "none"
    ARCHITECTURE: "x64"
    EXTRA_FLAGS: ""
  <<: *node_binary

build:src:stable:
  variables:
    CCACHE_DIR: "/root/.ccache"
    BUILD_TYPE: "stable"
    NODE_VERSION: "10"
    GIT_STRATEGY: "none"
    ARCHITECTURE: "x64"
    EXTRA_FLAGS: ""
  <<: *node_binary

.build:src:latest:arm64:
  variables:
    CCACHE_DIR: "/root/.ccache"
    BUILD_TYPE: "latest-arm64"
    NODE_VERSION: "12"
    GIT_STRATEGY: "none"
    ARCHITECTURE: "arm64"
  <<: *node_binary
  allow_failure: true

.build:src:stable:arm64:
  variables:
    CCACHE_DIR: "/root/.ccache"
    BUILD_TYPE: "stable-arm64"
    NODE_VERSION: "10"
    GIT_STRATEGY: "none"
    ARCHITECTURE: "arm64"
  <<: *node_binary
  allow_failure: true

build:slim:latest:
  needs:
    - build:src:latest
    - download:versions
  variables:
    BUILD_TYPE: "latest"
    NODE_VERSION: "12"
  <<: *slim_build

build:slim:stable:
  needs:
    - build:src:stable
    - download:versions
  variables:
    BUILD_TYPE: "stable"
    EXTRA_TAGS: "lts-slim,dubnium-slim,"
    NODE_VERSION: "10"
  <<: *slim_build

build:latest:
  needs:
    - download:versions
    - build:slim:latest
  variables:
    BUILD_TYPE: "latest"
    NODE_VERSION: "12"
  <<: *full_build

build:stable:
  needs:
    - build:slim:stable
    - download:versions
  variables:
    BUILD_TYPE: "stable"
    NODE_VERSION: "10"
    EXTRA_TAGS: "lts,dubnium,"
  <<: *full_build

scan:stable:
  needs:
    - build:stable
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:10
    GIT_STRATEGY: none

scan:latest:
  needs:
    - build:latest
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:12
    GIT_STRATEGY: none
