image: docker:latest

variables:
  IMG_NAME: "jitesoft/node-base"
  GREP_ARG: (?<=${BUILD_TYPE}=)(([0-9]{0,3}(\.?)){3})

stages:
  - build
  - slim
  - full

build:shared:
  stage: build
  variables:
    DOCKER_FILE: "shared/Dockerfile"
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:shared -f ${DOCKER_FILE} --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}:shared

.build:slim: &slim_build
  stage: slim
  before_script:
    - apk add --no-cache grep
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - docker pull ${CI_REGISTRY_IMAGE}:shared
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - NODE=$(docker inspect ${CI_REGISTRY_IMAGE}:shared | grep -oPm1 ${GREP_ARG})
    - NODE_SHORT="${NODE:0:1}"
    - echo "Building slim image for node v ${NODE} - short name ${NODE_SHORT}"
    - BUILD=$(docker build --build-arg VERSION=${NODE} -q -f ${DOCKER_FILE} --no-cache .)
    - echo "The image build hash is ${BUILD}"
    - TAGS="${NODE}-slim ${NODE_SHORT}-slim ${BUILD_TYPE}-slim"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done

build:slim:latest:
  variables:
    BUILD_TYPE: "latest"
    DOCKER_FILE: "slim/Dockerfile"
  <<: *slim_build

build:slim:stable:
  variables:
    BUILD_TYPE: "stable"
    BASE_TAGS: "stable-slim"
    DOCKER_FILE: "slim/Dockerfile"
  <<: *slim_build

.build:full: &full_build
  stage: full
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker pull jitesoft/node-base:${BUILD_TYPE}-slim
  script:
    - apk add --no-cache grep
    - NODE=$(docker inspect jitesoft/node-base:${BUILD_TYPE}-slim | grep -oPm1 ${GREP_ARG})
    - NODE_SHORT="${NODE:0:1}"
    - echo "Building full image for node v ${NODE} - short name ${NODE_SHORT}"
    - BUILD=$(docker build --build-arg BUILD_TYPE=${BUILD_TYPE} -q -f ${DOCKER_FILE} --no-cache .)
    - echo "The image build hash is ${BUILD}"
    - TAGS="${NODE} ${NODE_SHORT} ${BASE_TAGS} ${BUILD_TYPE}"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done

build:latest:
  variables:
    BUILD_TYPE: "latest"
    DOCKER_FILE: "full/Dockerfile"
  <<: *full_build

build:stable:
  variables:
    BUILD_TYPE: "stable"
    DOCKER_FILE: "full/Dockerfile"
  <<: *full_build
