image: docker:latest

variables:
  TAG: $CI_COMMIT_REF_NAME


before_script:
  - docker info
  - eval `[[ "$TAG" = "master" ]] && $TAG="latest" || $TAG="$TAG"`
  - echo $TAG

deploy:
  stage: deploy
  script:
    - docker build -t jitesoft/node-base:$TAG -t registry.gitlab.com/jitesoft/dockerfiles/node-base:$TAG . 
    - docker login -u $HUB_USER -p $HUB_PW
    - docker push jitesoft/node-base:$TAG
    - docker logout
    - docker login -u gitlab-ci-token -p $GITLAB_CI_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/jitesoft/dockerfiles/node-base:$TAG
    - docker logout
