image: docker:latest

variables:
  IMG_NAME: "jitesoft/node-base"

stages:
  - build
  - slim
  - full

build:shared:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:shared -f shared/Dockerfile --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}:shared

.build:slim: &slim_build
  stage: slim
  before_script:
    - apk add --no-cache grep
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - docker pull ${CI_REGISTRY_IMAGE}:shared
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - NODE=$(docker run --rm ${CI_REGISTRY_IMAGE}:shared cat /tmp/${BUILD_TYPE}.txt)
    - NODE_SHORT="${NODE:0:1}"
    - echo "Building slim image for node v ${NODE} - short name ${NODE_SHORT}"
    - BUILD=$(docker build --build-arg VERSION=${NODE} -q -f slim/Dockerfile --no-cache .)
    - echo "The image build hash is ${BUILD}"
    - TAGS="${NODE}-slim ${NODE_SHORT}-slim ${BUILD_TYPE}-slim ${EXTRA_TAGS}"
    - for tag in ${TAGS}; do docker tag ${BUILD} ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done

build:slim:latest:
  variables:
    BUILD_TYPE: "latest"
    EXTRA_TAGS: ''
  <<: *slim_build

build:slim:stable:
  variables:
    BUILD_TYPE: "stable"
    EXTRA_TAGS: "lts-slim carbon-slim"
  <<: *slim_build

.build:full: &full_build
  stage: full
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker pull jitesoft/node-base:${BUILD_TYPE}-slim
    - apk add --no-cache grep
  script:
    - NODE=$(docker run --rm jitesoft/node-base:${BUILD_TYPE}-slim env | grep NODE_VERSION | cut -d'=' -f2)
    - NODE_SHORT="${NODE:0:1}"
    - echo "Building full image for node v ${NODE} - short name ${NODE_SHORT}"
    - BUILD=$(docker build --build-arg BUILD_TYPE=${BUILD_TYPE} -q -f full/Dockerfile --no-cache .)
    - echo "The image build hash is ${BUILD}"
    - TAGS="${NODE} ${NODE_SHORT} ${BUILD_TYPE} ${EXTRA_TAGS}"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done

build:latest:
  variables:
    BUILD_TYPE: "latest"
  <<: *full_build

build:stable:
  variables:
    BUILD_TYPE: "stable"
    EXTRA_TAGS: "lts carbon"
  <<: *full_build
