image: docker:latest

before_script:
  - TAG=$([[ "$CI_COMMIT_REF_NAME" = "master" ]] && echo "latest" || echo $CI_COMMIT_REF_NAME)
  - echo $TAG
  - docker info

deploy:
  stage: deploy
  script:
    - docker build -t jitesoft/node-base:$TAG -t registry.gitlab.com/jitesoft/dockerfiles/node-base:$TAG . 
    - docker login -u $HUB_USER -p $HUB_PW
    - docker push jitesoft/node-base:$TAG
    - docker logout
    - docker login -u gitlab-ci-token -p $GITLAB_CI_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/jitesoft/dockerfiles/node-base:$TAG
    - docker logout
