image: docker:latest

variables:
  IMG_NAME: "jitesoft/node-base"

before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

latest:
  stage: deploy
  variables:
    DOCKER_FILE: "full/latest/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - echo "Building for node v ${NODE}. The image build hash is ${BUILD}"
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE} ${NODE_SHORT} latest"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
  only:
    - master

stable:
  stage: deploy
  variables:
    DOCKER_FILE: "full/stable/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - echo "Building for node v ${NODE}. The image build hash is ${BUILD}"
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE} ${NODE_SHORT} stable"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
  only:
    - master

latest_slim:
  stage: deploy
  variables:
    DOCKER_FILE: "slim/latest/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - echo "Building for node v ${NODE}. The image build hash is ${BUILD}"
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE}-slim ${NODE_SHORT}-slim latest-slim"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
  only:
    - master

stable_slim:
  stage: deploy
  variables:
    DOCKER_FILE: "slim/stable/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - echo "Building for node v ${NODE}. The image build hash is ${BUILD}"
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE}-slim ${NODE_SHORT}-slim stable-slim"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done
  only:
    - master