image: docker:latest

variables:
  IMG_NAME: "jitesoft/node-base"

stages:
  - build
  - slim
  - deploy

build:shared:
  stage: build
  variables:
    DOCKER_FILE: "shared/Dockerfile"
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:shared -f ${DOCKER_FILE} --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}:shared

.build:slim: &slim_build
  stage: slim
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:    
    - BUILD=$(docker build -q -f ${DOCKER_FILE} --no-cache .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - echo "Building for node v ${NODE}. The image build hash is ${BUILD}"
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE}-slim ${NODE_SHORT}-slim ${BASE_TAGS}"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done

build:slim:latest:
  variables:
    BASE_TAGS: "latest-slim"
    DOCKER_FILE: "slim/latest/Dockerfile"
  <<: *slim_build

build:slim:stable:
  variables:
    BASE_TAGS: "stable-slim"
    DOCKER_FILE: "slim/stable/Dockerfile"
  <<: *slim_build

.build:full: &full_build
  stage: deploy
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} --no-cache .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - echo "Building for node v ${NODE}. The image build hash is ${BUILD}"
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE} ${NODE_SHORT} ${BASE_TAGS}"
    - for tag in $TAGS; do docker tag $BUILD ${IMG_NAME}:${tag}; docker push ${IMG_NAME}:${tag}; done

build:latest:
  variables:
    DOCKER_FILE: "full/latest/Dockerfile"
    BASE_TAGS: "latest"
  <<: *full_build

build:stable:
  variables:
    DOCKER_FILE: "full/stable/Dockerfile"
    BASE_TAGS: "stable"
  <<: *full_build
